services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrms_pro
    ports:
      - "5432:5432"
    volumes:
      - hrms_pg_data:/var/lib/postgresql/data

volumes:
  hrms_pg_data:
